global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-mvc-traditional'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-mvc-traditional:8080']
        labels:
          application: 'spring-mvc-traditional'
          type: 'blocking-io'

  - job_name: 'spring-virtual-threads'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-virtual-threads:8081']
        labels:
          application: 'spring-virtual-threads'
          type: 'virtual-threads'

  - job_name: 'spring-webflux'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-webflux:8082']
        labels:
          application: 'spring-webflux'
          type: 'reactive-nio'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
